spring.datasource.url=jdbc:postgresql://localhost:5432/mindspace
spring.datasource.username=postgres
spring.datasource.password=3560
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.jwt.secret=mindspace-super-secret-jwt-key-2024-change-in-production
app.jwt.expiration=86400000

app.gemini.api-key=AQ.Ab8RN6JkAfxaAP3Mh-zAmz4Sbp8JCVu0O6MY6eK7OotAOF1cXA

spring.security.oauth2.client.registration.google.client-id=581878709171-535agfrq1cae8m4gk2mueobfa16gg3u8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile